serverRpc:
  host: 0.0.0.0
  port: 11500
serverMetrics:
  host: 0.0.0.0
  port: 5854
log:
  level: DEBUG
jwt:
  secret: 123456
  exp: 7
registry:
  type: "etcd"  # 可选: etcd, nacos
  enable: true   # 是否启用服务注册