nacos:
  endpoints: ["127.0.0.1:8848"]
  username: nacos
  password: nacos
  timeoutMs: 5000
  namespaceId: 2b829729-c3c4-4de7-aaed-8d6298222378
  cacheDir: cache_nacos/
  logDir: /tmp/nacos/logs
  logLevel: debug
  notLoadCacheAtStart: true